---
- hosts: ubuntu1404-builders
  tasks:
  - name: Add OpenContail PPA
    become: yes
    apt_repository:
      repo: "ppa:opencontrail/ppa"
  - name: Update package cache
    become: yes
    apt:
      update_cache: yes
  - name: Install OpenContrail building dependencies
    become: yes
    apt:
      name: "{{ item }}"
      state: present
    with_items:
    - git
    - cmake
    - autoconf
    - automake
    - bison
    - debhelper
    - flex
    - libcurl4-openssl-dev
    - libexpat-dev
    - libgettextpo0
    - libprotobuf-dev
    - libtool
    - libxml2-utils
    - make
    - protobuf-compiler
    - python-all
    - python-dev
    - python-lxml
    - python-setuptools
    - python-sphinx
    - ruby-ronn
    - scons
    - unzip
    - vim-common
    - libsnmp-python
    - libipfix-dev
    - librdkafka-dev
    - librdkafka1
    - libboost-dev
    - libboost-chrono-dev
    - libboost-date-time-dev
    - libboost-filesystem-dev
    - libboost-program-options-dev
    - libboost-python-dev
    - libboost-regex-dev
    - libboost-system-dev
    - libcurl4-openssl-dev
    - google-mock
    - libgoogle-perftools-dev
    - liblog4cplus-dev
    - libtbb-dev
    - libhttp-parser-dev
    - libxml2-dev
    - libicu-dev
    - libpcap-dev
    - libnl-genl-3-dev
    - libnl-3-dev
    - libzookeeper-mt-dev
    - libzookeeper-mt2
  - name: Install Linux kernel 3.13.0-85
    become: yes
    apt:
      name: "{{ item }}"
      state: present
    with_items:
    - linux-image-3.13.0-85-generic
    - linux-headers-3.13.0-85-generic
  - name: Remove newer kernels
    become: yes
    apt:
      name: "{{ item }}"
      state: absent
    with_items:
    - linux-image-4.4.0-103-generic
    - linux-headers-4.4.0-103-generic
    - linux-image-4.4.0-31-generic
    - linux-headers-4.4.0-31-generic
  - name: Create directory for Cassandra packages
    file:
      path: /tmp/cassandra
      state: directory
  - name: Download Cassandra packages
    get_url:
      url: "{{ item }}"
      dest: /tmp/cassandra
    with_items:
    - https://downloads.datastax.com/cpp-driver/ubuntu/14.04/cassandra/v2.2.0/cassandra-cpp-driver_2.2.0-1_amd64.deb
    - https://downloads.datastax.com/cpp-driver/ubuntu/14.04/cassandra/v2.2.0/cassandra-cpp-driver-dev_2.2.0-1_amd64.deb
    - https://downloads.datastax.com/cpp-driver/ubuntu/14.04/dependencies/libuv/v1.7.5/libuv_1.7.5-1_amd64.deb
  - name: Install Cassandra packages
    become: yes
    apt:
      deb: "/tmp/cassandra/{{ item }}"
      state: present
    with_items:
    - libuv_1.7.5-1_amd64.deb
    - cassandra-cpp-driver_2.2.0-1_amd64.deb
    - cassandra-cpp-driver-dev_2.2.0-1_amd64.deb

- hosts: ubuntu1404-builders
  tasks:
  - name: Install Jenkins slave dependencise
    become: yes
    apt:
      name: "{{ item }}"
      state: present
    with_items:
    - default-jre
  - name: Create user for Jenkins
    become: yes
    user:
      name: jenkins
      state: present
      shell: /bin/bash
  - name: Create Jenkins Slave workdir
    become: yes
    file:
      path: /home/jenkins/workdir
      state: directory
      owner: jenkins
      group: jenkins
  - name: Create ~/bin directory
    become: yes
    file:
      path: /home/jenkins/bin
      state: directory
      owner: jenkins
      group: jenkins
  - name: Create ~/.ssh directory
    become: yes
    file:
      path: /home/jenkins/.ssh
      state: directory
      owner: jenkins
      group: jenkins
  - name: Copy codijenkinsbot SSH keys
    become: yes
    copy:
      src: "{{ item }}"
      dest: /home/jenkins/.ssh/
      owner: jenkins
      group: jenkins
    with_items:
    - id_rsa
    - id_rsa.pub
  - name: Get github public SSH host key
    become: yes
    shell: ssh-keyscan github.com >> /home/jenkins/.ssh/known_hosts
  - name: Download repo tool
    become: yes
    get_url:
      url: https://storage.googleapis.com/git-repo-downloads/repo
      dest: /home/jenkins/bin
      mode: 0755
      owner: jenkins
      group: jenkins
