---
- name: Copy docker installer on remote machine
  win_copy:
     src: InstallDocker.msi
     dest: c:\InstallDocker.msi

- name: Installing docker
  win_msi:
     path: c:\InstallDocker.msi
     wait: true

- name: Copy contrail docker driver installer on remote machine
  win_copy:
     src: docker-driver.msi
     dest: c:\docker-driver.msi

- name: Installing contrail docker driver
  win_msi:
     path: c:\docker-driver.msi
     wait: true
