- name: Contrail for Windows installer
  hosts: all
  tasks:
    - name: Copy vRouter installer to remote machines
      win_copy:
        src: vRouter.msi
        dest: C:\Tmp\vRouter.msi

    - name: Installing vRouter
      win_msi:
        path: c:\Tmp\vRouter.msi
        wait: true

    - name: Copy utils installer to remote machines
      win_copy:
        src: utilsMSI.msi
        dest: c:\utilsMSI.msi

    - name: Installing utils
      win_msi:
        path: c:\utilsMSI.msi
        wait: true

    - name: Copy docker installer on remote machine
      win_copy:
        src: InstallDocker.msi
        dest: c:\InstallDocker.msi

    - name: Installing docker
      win_msi:
        path: c:\InstallDocker.msi
        wait: true

    - name: Copy contrail docker driver installer on remote machine 
      win_copy:
        src: installer.msi
        dest: c:\installer.msi

    - name: Installing contrail docker driver
      win_msi:
        path: c:\installer.msi
        wait: true
