#!/bin/bash

install_service () {
    echo "Installing service: $1..."
    if [ ! -f $1 ]; then
        echo "Error: File $1 does not exist."
        exit 1
    fi

    if ! cp --force $1 /etc/systemd/system; then
        echo "Error: Could not copy file $1 to /etc/systemd/system."
        exit 1
    fi

    if ! (systemctl enable $1 && systemctl start $1); then
        echo "Error: Service $1 can not be enabled/started."
        exit 1
    fi
}

disable_offloading () {
    echo "Switching checksum offloading off for interface $1..."
    if ! ethtool -K $1 rx off tx off; then
        echo "Error: Could not switch checksum offloading off..."
    fi
}

ifconfig | grep "Link encap:Ethernet" | cut --delimiter=' ' --fields=1 | while read -r interface; do disable_offloading $interface; done

install_service httpserver.service
install_service udpecho.service
echo "Done!"

